apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: phpfpm-claim0
  name: phpfpm-claim0
spec:
  volumeName: phpfpm-pv0001
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
status: {}
