apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  creationTimestamp: null
  name: phpmyadmin
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: phpmyadmin
    spec:
      containers:
      - env:
        - name: MYSQL_ROOT_PASSWORD
          value: testing12321
        - name: MYSQL_USERNAME
          value: root
        - name: PMA_HOST
          value: mysql
        image: phpmyadmin/phpmyadmin
        name: phpmyadmin
        ports:
        - containerPort: 8088
        resources: {}
      restartPolicy: Always
status: {}
