apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: nginx
  name: nginx
spec:
  type: NodePort
  ports:
    - name: nginx-port
      nodePort: 30880
      port: 80
      protocol: TCP
      targetPort: 80
  selector:
    io.kompose.service: nginx
status:
  loadBalancer: {}
#  NodePort range: 30000-32767