apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: nginx-claim2
  name: nginx-claim2
spec:
  volumeName: nginx-pv0003
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 10Mi
status: {}
