apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  creationTimestamp: null
  name: nginx
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: nginx
    spec:
      containers:
      - image: bitnami/nginx
        name: nginx
        ports:
        - containerPort: 80
        resources: {}
        volumeMounts:
        - mountPath: /opt/bitnami/nginx/logs/myapp-access.log
          name: nginx-claim0
        - mountPath: /opt/bitnami/nginx/logs/myapp-error.log
          name: nginx-claim1
        - mountPath: /bitnami/nginx/conf/vhosts/app.conf
          name: nginx-claim2
        - mountPath: /myapps
          name: nginx-claim3
      restartPolicy: Always
      volumes:
      - name: nginx-claim0
        persistentVolumeClaim:
          claimName: nginx-claim0
      - name: nginx-claim1
        persistentVolumeClaim:
          claimName: nginx-claim1
      - name: nginx-claim2
        persistentVolumeClaim:
          claimName: nginx-claim2
      - name: nginx-claim3
        persistentVolumeClaim:
          claimName: nginx-claim3
status: {}
