kind: PersistentVolume
apiVersion: v1
metadata:
  name: nginx-pv0001
  labels:
    type: local
spec:
  capacity:
    storage: 30Mi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/hosthome/secure/lemp/logs/access.log"
