kind: PersistentVolume
apiVersion: v1
metadata:
  name: nginx-pv0004
  labels:
    type: local
spec:
  capacity:
    storage: 300Mi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/hosthome/secure/lemp/public"
